# Main server settings
server:
  grpc_port: 50051
  tcp_port: 50052
  health_check_interval: "5s"

  # TLS configuration for the gRPC server
  tls:
    enabled: false
    cert_file: "certs/server.crt"
    key_file: "certs/server.key"

# Engine configuration for the core database
engine:
  # --- General ---
  data_dir: "./data"
  retention_period: "" # e.g., "720h" (30 days), "365d". Empty means disabled.
  metadata_sync_interval: "60s" # How often to sync metadata (manifest, etc.) to disk.

  # --- Memtable ---
  memtable:
    size_threshold_bytes: 4194304 # 4 MiB
    flush_interval: "1s" # Time-based flush interval. 0 to disable.

  # --- SSTable ---
  sstable:
    block_size_bytes: 8192 # 8 KiB
    compression: "snappy" # none, snappy, lz4, zstd
    bloom_filter_fp_rate: 0.01

  # --- Cache ---
  cache:
    # Number of SSTable data blocks to keep in the LRU cache.
    block_cache_capacity: 1024

  # --- Compaction ---
  compaction:
    l0_trigger_file_count: 4
    l0_trigger_size_bytes: 16777216 # 16 MiB
    target_sstable_size_bytes: 16777216 # 16 MiB
    levels_size_multiplier: 5
    max_levels: 7
    check_interval: "120s"
    fallback_strategy: "PickOldest"

  # --- Write-Ahead Log (WAL) ---
  wal:
    sync_mode: "interval" # "always", "batch", "interval", "disabled"
    batch_size: 1
    flush_interval: "1000ms"
    max_segment_size_bytes: 33554432 # 32 MiB
    purge_keep_segments: 4

  # --- Tag Index ---
  index:
    memtable_threshold: 10000 # Number of unique tag pairs
    flush_interval: "60s"
    compaction_check_interval: "20s"
    l0_trigger_file_count: 4
    base_target_size_bytes: 2097152 # 2 MiB

# --- Other Services ---

# Logging configuration
logging:
  level: "debug"   # "debug", "info", "warn", "error"
  output: "stdout" # "stdout", "file", "none"
  file: "nexusbase.log" # Path for 'file' output

# Security settings (Authentication)
security:
  enabled: false
  user_file_path: "data/users.db"

# Self-monitoring settings
self_monitoring:
  enabled: true
  interval: "5s"
  metric_prefix: "__"

# Web-based Query UI
query_server:
  enabled: true
  listen_address: "0.0.0.0:8088"

# Distributed Tracing (OTLP)
tracing:
  enabled: false
  endpoint: "localhost:4317" # e.g., "otel-collector:4317"
  protocol: "grpc" # "grpc" or "http"

# Debugging endpoints (pprof, expvar)
debug:
  enabled: true
  listen_address: "0.0.0.0:6060"
  pprof_enabled: true
  metrics_enabled: true # Exposes /debug/vars (expvar)
  monitor_ui_enabled: true # Exposes /debug/statsviz