name: Publish Tag

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Type of version (major, minor or patch)'
        required: true
        type: choice
        default: 'patch'
        options:
          - 'major'
          - 'minor'
          - 'patch'

jobs:
  publish:
    name: Create and Publish Tag
    runs-on: ubuntu-latest
    environment: "tag-release"
    permissions:
      # Needed to create and push a tag
      contents: write
      # Needed by wait-on-check-action to query workflow statuses
      actions: read
      checks: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'main'
          # Fetch all history for semantic-versioning to work correctly
          fetch-depth: 0
          submodules: true

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Tag snapshot
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.version.outputs.version }}
